# Calculator on two variables a and b
a = int(input("Enter an integer as input:"))
b = int(input("Enter second integer as input"))
print("Addition", a+b)
print("Subtraction", a-b)
print("Multiplication", a*b)
print("Division", a/b)
print("Exponential", a**b)
print("quotient on a is divided by b", a//b)
print("remainder on a is divided by b", a%b)
